### ISSUE TITLE
error when importing...

### ISSUE THREAD

**Issue by beetaa** [AstrorEnales/blender_magicavoxel#6]
blender 3.2
importer 1.2.3

![image](https://user-images.githubusercontent.com/5688224/177785571-30ea8115-7a30-44a3-841a-2e480bf8b708.png)

**Comment by beetaa** [comment]
[chr_knight.zip](https://github.com/AstrorEnales/blender_magicavoxel/files/9064092/chr_knight.zip)

the file is just get from magicavoxel's itself. for your convinent, I've upload here.

**Comment by AstrorEnales** [comment]
@beetaa Thank you for reporting this issue. May i ask from which version of MagicaVoxel this file is? I checked the chr_knight.vox file from version 0.99.7.0 as well as 0.99.3 and both worked fine. I looked into your supplied file using my vox-viewer and it contains only very few information, so i suspect it coming from an older MagicaVoxel version. Nonetheless, i should be able to quickly provide a small fix.

**Comment by beetaa** [comment]
@AstrorEnales Thank you so much for your nice and hard work. I use 0.99.7.0(beta) currently, and the model is come from [MagicaVoxel's resource repo](https://github.com/ephtracy/voxel-model/tree/master/vox/character), you're right, the model maybe generated several years ago with the old version.

**Comment by AstrorEnales** [comment]
Oh i see, yeah, the models in that repo are 7 years old ^^ I thought you meant the models from the "vox" folder bundled with the installed program. I implemented a small fix for this issue and will publish a new version tomorrow together with some other improvements. In the meantime you can also download the python file from the source code directly.
If you encounter anything else, i'm always happy to help.
