### ISSUE TITLE
Using "Greedy mesh" and "Material per colour" options cause missing voxels

### ISSUE THREAD

**Issue by ZsoltHevesi** [AstrorEnales/blender_magicavoxel#9]
When using the Greedy mesh option on a small Vox file:
[rockingChair.zip](https://github.com/AstrorEnales/blender_magicavoxel/files/14238536/rockingChair.zip)

The corner cube on the bottom disappears. I use these corner blocks to scale the model as a whole to fit a grid in a project of mine, but I fear it can cause other missing voxels.

Tested using Blender 3.6

**Comment by AstrorEnales** [comment]
Thanks for reporting this bug, i could reproduce it. This is likely an edge case of the new data structure but easily fixable. Will check it out today and let you know once it's fixed.

**Comment by AstrorEnales** [comment]
The issue is fixed and a new release available for download. It was a small error that snuck in while porting the new data structure. Thanks again for reporting!
